include:
  - project: 'home9344428/cicd/templates'
    ref: 'main'
    file: '/PyPi/build_and_publish.yml'

stages:
  - build
  - release
  - deploy

pages:
  image: antora/antora
  stage: deploy
  script:
    - sed -i 's/<authentication>@/${DEPLOY_USERNAME}:${DEPLOY_PASSWORD}@/' antora-playbook.yml
    - antora --fetch --redirect-facility=gitlab --to-dir=public antora-playbook.yml
  artifacts:
    paths:
      - public