site:
  title: SysBot
  start_page: sysbot:sysbot:index.adoc
content:
  sources:
  - url: https://oauth2:<CI_JOB_TOKEN>@gitlab.com/home9344428/app/sysbot/sysbot.git
    branches: HEAD
    start_path: docs
  - url: https://oauth2:<CI_JOB_TOKEN>@gitlab.com/home9344428/app/sysbot/sysbotRedhat.git
    branches: HEAD
    start_path: docs
  - url: https://oauth2:<CI_JOB_TOKEN>@gitlab.com/home9344428/app/sysbot/sysbotWindows.git
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true